### ISSUE TITLE
page.handle_webhook does not handle empty message

### ISSUE THREAD

**Issue by Hari-Sheng** [conbus/fbmq#28] opened 2017-08-17 20:51 UTC
Not sure if this is due to an API change. For webhook POST payload:
```
{"object":"page","entry":[{"id":"214236215771147","time":1502997235746,"standby":[{"recipient":{"id":"214236215771147"},"timestamp":1502997235746,"sender":{"id":"1437928559577569"},"postback":{"title":"Get Started"}}]}]}
```
I get the following exception:
```
2017-08-17T19:13:59.463799+00:00 app[web.1]: [2017-08-17 19:13:59,463] ERROR in app: Exception on /webhook [POST]
2017-08-17T19:13:59.463801+00:00 app[web.1]: Traceback (most recent call last):
2017-08-17T19:13:59.463802+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
2017-08-17T19:13:59.463803+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-08-17T19:13:59.463804+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-08-17T19:13:59.463805+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-08-17T19:13:59.463805+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-08-17T19:13:59.463806+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-08-17T19:13:59.463806+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
2017-08-17T19:13:59.463807+00:00 app[web.1]:     raise value
2017-08-17T19:13:59.463808+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-08-17T19:13:59.463809+00:00 app[web.1]:     rv = self.dispatch_request()
2017-08-17T19:13:59.463809+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
2017-08-17T19:13:59.463810+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-08-17T19:13:59.463811+00:00 app[web.1]:   File "/app/server/server.py", line 48, in webhook
2017-08-17T19:13:59.463811+00:00 app[web.1]:     page.handle_webhook(payload)
2017-08-17T19:13:59.463812+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fbmq/fbmq.py", line 204, in handle_webhook
2017-08-17T19:13:59.463813+00:00 app[web.1]:     for event in get_events(data):
2017-08-17T19:13:59.463813+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/fbmq/fbmq.py", line 200, in get_events
2017-08-17T19:13:59.463814+00:00 app[web.1]:     for messaging in entry.get("messaging"):
2017-08-17T19:13:59.463846+00:00 app[web.1]: TypeError: 'NoneType' object is not iterable
```
It seems that the case that webhook payload does not have message is not handled [here](https://github.com/conbus/fbmq/blob/master/fbmq/fbmq.py#L198)

**Comment by anmv** [comment] 2017-09-14 12:12
I have the same problem. Can you fix it?

**Comment by zinwalin** [comment] 2017-09-17 22:39
same here.

**Comment by fbaeumer** [comment] 2017-10-25 11:27
same here :(

**Comment by anton-nayshtut** [comment] 2017-10-25 12:01
The issue is caused by [standby (beta) Webhook Event Reference](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/standby/) that introduces new "channel" - standby. 

The fix will be committed soon.

**Closed** 2017-10-25 12:05 UTC
